In [1]:
#import 
from utils import *
from utils.data_processing import Ego4d_NLQ
from collections import defaultdict
import pandas as pd
import numpy as np
from collections import Counter
import json
from copy import deepcopy

c:\users\sreerag\appdata\local\programs\python\python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\users\sreerag\appdata\local\programs\python\python39\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
c:\users\sreerag\appdata\local\programs\python\python39\lib\site-packages\numpy\.libs\libopenblas.JPIJNSWNNAN3CE6LLI5FWSPHUT2VXMTH.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
dataSetRoot = "../fb-ego4d/ego4d_data/" #"./dataset/tmp/"
ego4d_json = dataSetRoot + "ego4d.json"
v1_root = dataSetRoot + "v1/"
annotation_root = v1_root + "annotations/"

In [ ]:
ego4D = Ego4d(ego4d_json)

In [3]:
nql_train = annotation_root + "nlq_train.json"
nql_val = annotation_root + "nlq_val.json"

In [4]:
nql_dataset_train = Ego4d_NLQ(nql_train)
nql_dataset_val = Ego4d_NLQ(nql_val)

#train frames: 0
#train clips: 0
No Data Loaded!
defaultdict(<class 'int'>, {})
#train frames: 0
#train clips: 0
No Data Loaded!
defaultdict(<class 'int'>, {})


In [ ]:
vq_train = annotation_root + "vq_train.json"
vq_val = annotation_root + "vq_val.json"

In [ ]:
vq_dataset_train = Ego4d_VQ(vq_train)
vq_dataset_val = Ego4d_VQ(vq_val)

In [ ]:
mq_train = annotation_root + "moments_train.json"
mq_val = annotation_root + "moments_val.json"

In [ ]:
mq_dataset_train = Ego4d_MQ(mq_train)
mq_dataset_val = Ego4d_MQ(mq_val)

In [ ]:
vq_train = annotation_root + "vq_train.json"
vq_val = annotation_r#from collections import defaultdict
video_clip_len = defaultdict(int)
for _id, clip_ids in nql_dataset.video_clip.items():
    secs = 0
    for _c_id in clip_ids:
        clip = nql_dataset.clips[_c_id]
        secs += clip['video_end_sec'] - clip['video_start_sec']
    video_clip_len[_id] = int(secs//60)
video_clip_len

In [ ]:
#from collections import defaultdict
video_clip_val_len = defaultdict(int)
for _id, clip_ids in nql_dataset_val.video_clip.items():
    secs = 0
    for _c_id in clip_ids:
        clip = nql_dataset_val.clips[_c_id]
        secs += clip['video_end_sec'] - clip['video_start_sec']
    video_clip_val_len[_id] = int(secs//60)
video_clip_val_len

In [ ]:
video_length = 0
clip_length = 0
for _id, m in video_clip_len.items():
    video_length += video_len[_id]
    clip_length += m

In [ ]:
video_length_val = 0
clip_length_val = 0
for _id, m in video_clip_val_len.items():
    video_length_val += video_len[_id]
    clip_length_val += m

In [ ]:
import pandas as pd

In [ ]:
print(video_length//len(video_clip_len.keys()), clip_length//len(video_clip_len.keys()))

In [ ]:
print(video_length_val//len(video_clip_val_len.keys()), clip_length_val//len(video_clip_val_len.keys()))

In [ ]:
video_clip_len_df = pd.DataFrame.from_dict(video_clip_len.items())
video_len_df = pd.DataFrame.from_dict(video_len.items())
print(video_clip_len_df.head())
print(video_len_df.head())

In [ ]:
len(video_clip_len_df)

In [ ]:
len(video_clip_len_df[video_clip_len_df[1] > 5])

In [ ]:
print(video_clip_len_df[1].mean(), video_clip_len_df[1].max(), video_clip_len_df[1].min())

In [ ]:
video_clip_val_len_df = pd.DataFrame.from_dict(video_clip_val_len.items())
video_len_df = pd.DataFrame.from_dict(video_len.items())
print(video_clip_len_df.head())
print(video_len_df.head())

In [ ]:
len(video_clip_val_len_df)

In [ ]:
len(video_clip_val_len_df[video_clip_val_len_df[1] > 5])

In [ ]:
print(video_clip_val_len_df[1].mean(), video_clip_val_len_df[1].max(), video_clip_val_len_df[1].min())

In [ ]:
len(ego4D.videos.keys())

In [ ]:
print(len(nql_dataset_train.videos.keys()), len(nql_dataset_val.videos.keys()), len(vq_dataset_train.videos.keys()), len(vq_dataset_val.videos.keys()), len(mq_dataset_train.videos.keys()), len(mq_dataset_val.videos.keys()))

In [ ]:
print(len(nql_dataset_train.clips.keys()), len(nql_dataset_val.clips.keys()), len(vq_dataset_train.clips.keys()), len(vq_dataset_val.clips.keys()), len(mq_dataset_train.clips.keys()), len(mq_dataset_val.clips.keys()))

In [ ]:
nlq_video_train_ids = set(nql_dataset_train.videos.keys())
nlq_video_val_ids = set(nql_dataset_val.videos.keys())
vq_video_train_ids = set(vq_dataset_train.videos.keys())
vq_video_val_ids = set(vq_dataset_val.videos.keys())
mq_video_train_ids = set(mq_dataset_train.videos.keys())
mq_video_val_ids = set(mq_dataset_val.videos.keys())

In [ ]:
nlq_union = nlq_video_train_ids.union(nlq_video_val_ids)
vq_union = vq_video_train_ids.union(vq_video_val_ids)
mq_union = mq_video_train_ids.union(mq_video_val_ids)

print(len(nlq_union), len(vq_union), len(mq_union))

In [ ]:
nlq_vq_mq_intersection = nlq_union.intersection(vq_union.intersection(mq_union))

print(len(nlq_vq_mq_intersection))

In [ ]:
duration_sec = 0 
audio_sec = 0
video_duration = defaultdict(int)
audio_duration = defaultdict(int)
for _id in nlq_vq_mq_intersection:
    duration_sec += ego4D.videos[_id]['duration_sec']
    audio_sec += ego4D.videos[_id]['video_metadata']['audio_duration_sec'] if ego4D.videos[_id]['video_metadata']['audio_duration_sec'] != None else 0
    video_duration[_id] = int(ego4D.videos[_id]['duration_sec']//60)
    audio_duration[_id] = int((ego4D.videos[_id]['video_metadata']['audio_duration_sec'] if ego4D.videos[_id]['video_metadata']['audio_duration_sec'] != None else 0)//60)
print( duration_sec//60, 'min,' ,duration_sec//3600, 'hr - of footage')
print(duration_sec//len(nlq_vq_mq_intersection)//60, 'min - average length of video' )
print( audio_sec//60, 'min,' ,audio_sec//3600, 'hr - of audio')
print(audio_sec//len(nlq_vq_mq_intersection)//60, 'min - average length of video' )

In [ ]:
videolength_df = pd.DataFrame.from_dict(video_duration.items())
videolength_df.head()

In [ ]:
audiolength_df = pd.DataFrame.from_dict(audio_duration.items())
audiolength_df.head()

In [ ]:
v_len = 100
print(videolength_df[1].sum(), audiolength_df[1].sum())
print(len(videolength_df[videolength_df[1]<v_len]), len(videolength_df[videolength_df[1]>v_len]), " less than : greater than ", videolength_df[videolength_df[1]<v_len][1].sum(), videolength_df[videolength_df[1]>v_len][1].sum(), "min")
print(len(audiolength_df[videolength_df[1]<v_len]), len(audiolength_df[videolength_df[1]>v_len]), " less than : greater than ", audiolength_df[videolength_df[1]<v_len][1].sum(), audiolength_df[videolength_df[1]>v_len][1].sum(), "min")
print("Video and audio length are same: ",len(audiolength_df[audiolength_df[1] == videolength_df[1]]))
temp_videolength_df = videolength_df[audiolength_df[1] == videolength_df[1]]
print(temp_videolength_df[1].sum(), 'min')
print(len(temp_videolength_df[temp_videolength_df[1]<v_len]), len(temp_videolength_df[temp_videolength_df[1]>v_len]), " less than : greater than " , temp_videolength_df[temp_videolength_df[1]<v_len][1].sum(), temp_videolength_df[temp_videolength_df[1]>v_len][1].sum(), "min")

In [ ]:
sameavlen_nlq_vq_mq_intersection = set(temp_videolength_df[0].to_numpy())
sameavlen_nlq_vq_mq_intersection

In [ ]:
scenarios = defaultdict(set)
split = defaultdict(set)
for _id in nlq_vq_mq_intersection:
    for s in ego4D.videos[_id]['scenarios']:
        scenarios[s].add(_id)
    split[ego4D.videos[_id]['split_em']].add(_id)

In [ ]:
print(len(scenarios.keys()), scenarios.keys())

In [ ]:
print('train: ',len(split['train']), 'val: ',len(split['val']))

In [ ]:
scenarios = defaultdict(set)
split = defaultdict(set)
for _id in sameavlen_nlq_vq_mq_intersection:
    for s in ego4D.videos[_id]['scenarios']:
        scenarios[s].add(_id)
    split[ego4D.videos[_id]['split_em']].add(_id)

In [ ]:
print(len(scenarios.keys()), scenarios.keys())

In [ ]:
print('train: ',len(split['train']), 'val: ',len(split['val']))

In [ ]:
sameavlen_nlq_vq_mq_intersection = set(temp_videolength_df[temp_videolength_df[1]<v_len][0].to_numpy())
#sameavlen_nlq_vq_mq_intersection

In [ ]:
scenarios = defaultdict(set)
split = defaultdict(set)
for _id in sameavlen_nlq_vq_mq_intersection:
    for s in ego4D.videos[_id]['scenarios']:
        scenarios[s].add(_id)
    split[ego4D.videos[_id]['split_em']].add(_id)

In [ ]:
print(len(scenarios.keys()), scenarios.keys())

In [ ]:
print('train: ',len(split['train']), 'val: ',len(split['val']))

In [ ]:
ids = ''
for i, s in enumerate(sameavlen_nlq_vq_mq_intersection):
    ids += s
    if i!= (len(sameavlen_nlq_vq_mq_intersection)-1):
        ids += ' '

In [ ]:
import csv

In [ ]:
f = open('./less_25.csv', 'w')
writer = csv.writer(f)
for i in list(sameavlen_nlq_vq_mq_intersection):
    writer.writerow([i])
f.close()

In [ ]:
ids

In [ ]:
file1 = open("./less_25.txt","w")
file1.write(ids)
file1.close()

In [ ]:
scenarios = defaultdict(set)
for _id, v in ego4D.videos.items():
    for s in v['scenarios']:
        scenarios[s].add(_id)

In [ ]:
len(scenarios['Farmer'])

In [ ]:
ids = ''
scenes = list(scenarios['Farmer'])[:10]
for i, s in enumerate(scenes):
    ids += s
    if i!= (len(scenes)-1):
        ids += ' '

In [ ]:
file1 = open("./less_farming.txt","w")
file1.write(ids)
file1.close()

In [ ]:
audio = defaultdict(int)
for i, v in ego4D.videos.items():
    audio[i] = v['video_metadata']['audio_duration_sec']

audio_df = pd.DataFrame.from_dict(audio.items())
audio_df.head()

In [ ]:
nql_dataset_train.clips['fae92e70-88aa-4b77-b41a-5879b74c804c']

In [ ]:
clipAudio_nlq_train = set()
for _id, c in nql_dataset_train.clips.items():
        videoStart = c['clip_start_sec']
        videoEnd = c['clip_end_sec']
        if nql_dataset_train.clip_video[_id] not in ego4D.videos:
            continue
        video = ego4D.videos[nql_dataset_train.clip_video[_id]]
        audioStart = video['video_metadata']['audio_start_sec']
        if video['video_metadata']['audio_duration_sec'] == None:
            continue
        audioEnd = video['video_metadata']['audio_start_sec'] + video['video_metadata']['audio_duration_sec']
        if videoStart >= audioStart and videoStart <= audioEnd and videoEnd >= audioStart and videoEnd <= audioEnd :
            clipAudio_nlq_train.add(_id)

clipAudio_nlq_val = set()
for _id, c in nql_dataset_val.clips.items():
        videoStart = c['clip_start_sec']
        videoEnd = c['clip_end_sec']
        if nql_dataset_val.clip_video[_id] not in ego4D.videos:
            continue
        video = ego4D.videos[nql_dataset_val.clip_video[_id]]
        audioStart = video['video_metadata']['audio_start_sec']
        if video['video_metadata']['audio_duration_sec'] == None:
            continue
        audioEnd = video['video_metadata']['audio_start_sec'] + video['video_metadata']['audio_duration_sec']
        if videoStart >= audioStart and videoStart <= audioEnd and videoEnd >= audioStart and videoEnd <= audioEnd :
            clipAudio_nlq_val.add(_id)

clipAudio_vq_train = set()
for _id, c in vq_dataset_train.clips.items():
        videoStart = c['clip_start_sec']
        videoEnd = c['clip_end_sec']
        if vq_dataset_train.clip_video[_id] not in ego4D.videos:
            continue
        video = ego4D.videos[vq_dataset_train.clip_video[_id]]
        audioStart = video['video_metadata']['audio_start_sec']
        if video['video_metadata']['audio_duration_sec'] == None:
            continue
        audioEnd = video['video_metadata']['audio_start_sec'] + video['video_metadata']['audio_duration_sec']
        if videoStart >= audioStart and videoStart <= audioEnd and videoEnd >= audioStart and videoEnd <= audioEnd :
            clipAudio_vq_train.add(_id)

clipAudio_vq_val = set()            
for _id, c in vq_dataset_val.clips.items():
        videoStart = c['clip_start_sec']
        videoEnd = c['clip_end_sec']
        if vq_dataset_val.clip_video[_id] not in ego4D.videos:
            continue
        video = ego4D.videos[vq_dataset_val.clip_video[_id]]
        audioStart = video['video_metadata']['audio_start_sec']
        if video['video_metadata']['audio_duration_sec'] == None:
            continue
        audioEnd = video['video_metadata']['audio_start_sec'] + video['video_metadata']['audio_duration_sec']
        if videoStart >= audioStart and videoStart <= audioEnd and videoEnd >= audioStart and videoEnd <= audioEnd :
            clipAudio_vq_val.add(_id)

clipAudio_mq_train = set()
for _id, c in mq_dataset_train.clips.items():
        videoStart = c['clip_start_sec']
        videoEnd = c['clip_end_sec']
        if mq_dataset_train.clip_video[_id] not in ego4D.videos:
            continue
        video = ego4D.videos[mq_dataset_train.clip_video[_id]]
        audioStart = video['video_metadata']['audio_start_sec']
        if video['video_metadata']['audio_duration_sec'] == None:
            continue
        audioEnd = video['video_metadata']['audio_start_sec'] + video['video_metadata']['audio_duration_sec']
        if videoStart >= audioStart and videoStart <= audioEnd and videoEnd >= audioStart and videoEnd <= audioEnd :
            clipAudio_mq_train.add(_id)
        
clipAudio_mq_val = set()
for _id, c in mq_dataset_val.clips.items():
        videoStart = c['clip_start_sec']
        videoEnd = c['clip_end_sec']
        if mq_dataset_val.clip_video[_id] not in ego4D.videos:
            continue
        video = ego4D.videos[mq_dataset_val.clip_video[_id]]
        audioStart = video['video_metadata']['audio_start_sec']
        if video['video_metadata']['audio_duration_sec'] == None:
            continue
        audioEnd = video['video_metadata']['audio_start_sec'] + video['video_metadata']['audio_duration_sec']
        if videoStart >= audioStart and videoStart <= audioEnd and videoEnd >= audioStart and videoEnd <= audioEnd :
            clipAudio_mq_val.add(_id)

In [ ]:
print(len(nql_dataset_train.clips.keys()), len(nql_dataset_val.clips.keys()), len(clipAudio_nlq_train),len(clipAudio_nlq_val) )
print(len(vq_dataset_train.clips.keys()), len(vq_dataset_val.clips.keys()), len(clipAudio_vq_train), len(clipAudio_vq_val))
print(len(mq_dataset_train.clips.keys()), len(mq_dataset_val.clips.keys()), len(clipAudio_mq_train), len(clipAudio_mq_val))

In [ ]:
video_ids_nql_train = set()
for _id in clipAudio_nlq_train:
    video_ids_nql_train.add(nql_dataset_train.clip_video[_id])

video_ids_nql_val = set()
for _id in clipAudio_nlq_val:
    video_ids_nql_val.add(nql_dataset_val.clip_video[_id])
    
video_ids_vq_train = set()
for _id in clipAudio_vq_train:
    video_ids_vq_train.add(vq_dataset_train.clip_video[_id])
    
video_ids_vq_val = set()
for _id in clipAudio_vq_val:
    video_ids_vq_val.add(vq_dataset_val.clip_video[_id])
    
video_ids_mq_train = set()
for _id in clipAudio_mq_train:
    video_ids_mq_train.add(mq_dataset_train.clip_video[_id])
    
video_ids_mq_val = set()
for _id in clipAudio_mq_val:
    video_ids_mq_val.add(mq_dataset_val.clip_video[_id])

In [ ]:
print(len(nql_dataset_train.videos.keys()),len(nql_dataset_val.videos.keys()),len(vq_dataset_train.videos.keys()),len(vq_dataset_val.videos.keys()),len(mq_dataset_train.videos.keys()),len(mq_dataset_val.videos.keys()))
print(len(video_ids_nql_train),len(video_ids_nql_val),len(video_ids_vq_train),len(video_ids_vq_val),len(video_ids_mq_train),len(video_ids_mq_val))

In [ ]:
nlq_union = video_ids_nql_train.union(video_ids_nql_val)
vq_union = video_ids_vq_train.union(video_ids_vq_val)
mq_union = video_ids_mq_train.union(video_ids_mq_val)

In [ ]:
print(len(nlq_union), len(vq_union),len(mq_union))

In [ ]:
nlq_vq_mq = nlq_union.intersection(vq_union.intersection(mq_union))
len(nlq_vq_mq)

In [ ]:
clip_nql_union = clipAudio_nlq_train.union(clipAudio_nlq_val)
clip_vq_union = clipAudio_vq_train.union(clipAudio_vq_val)
clip_mq_union = clipAudio_mq_train.union(clipAudio_mq_val)
print(len(clip_nql_union), len(clip_vq_union), len(clip_mq_union))

In [ ]:
clip_nlq_vq_mq = clip_nql_union.union(clip_vq_union.union(clip_mq_union))
len(clip_nlq_vq_mq)

In [ ]:
video_clips = defaultdict(set)
for _id in clipAudio_nlq_train:
    idx = nql_dataset_train.clip_video[_id]
    if idx in nlq_vq_mq:
        video_clips[idx].add(_id)

for _id in clipAudio_nlq_val:
    idx = nql_dataset_val.clip_video[_id]
    if idx in nlq_vq_mq:
        video_clips[idx].add(_id)

for _id in clipAudio_vq_train:
    idx = vq_dataset_train.clip_video[_id]
    if idx in nlq_vq_mq:
        video_clips[idx].add(_id)

for _id in clipAudio_vq_val:
    idx = vq_dataset_val.clip_video[_id]
    if idx in nlq_vq_mq:
        video_clips[idx].add(_id)

for _id in clipAudio_mq_train:
    idx = mq_dataset_train.clip_video[_id]
    if idx in nlq_vq_mq:
        video_clips[idx].add(_id)
    
for _id in clipAudio_mq_val:
    idx = mq_dataset_val.clip_video[_id]
    if idx in nlq_vq_mq:
        video_clips[idx].add(_id)    

In [ ]:
video_clips

In [ ]:
video_clips_df = pd.DataFrame.from_dict(video_clips.items())
video_clips_df['Length'] = video_clips_df[1].str.len()
video_clips_df.head()

In [ ]:
ax = video_clips_df.plot.bar( y='Length', rot=0, figsize=(30, 10))

In [ ]:
video_clips_3 = video_clips_df[video_clips_df['Length'] <= 3 ]

In [ ]:
ids = ''
for i, s in enumerate(sameavlen_nlq_vq_mq_intersection):
    ids += s
    if i!= (len(sameavlen_nlq_vq_mq_intersection)-1):
        ids += ' '
for i, c in enumerate(video_clips_3[1]):
    for j, _id in enumerate(c):
        ids += _id
        if i 

In [ ]:
file1 = open("./less_3.txt","w")
file1.write(ids)
file1.close()

In [ ]:
with av.open(clips_path) as input_video:
    stream = input_video.streams.audio
    print(stream)    

In [ ]:
import moviepy.editor as mp

In [ ]:
clips_path = v1_root + 'clips/1c6f2ab7-1088-45d6-b172-8bbd2ded74ac.mp4'
my_clip = mp.VideoFileClip(clips_path)

In [ ]:
my_clip

In [ ]:
my_clip.audio.write_audiofile(r"my_result.mp3")

In [ ]:
import glob, os

In [ ]:
file_paths = defaultdict(str)
for root, dirs, files in os.walk("./dataset/tmp/v1/clips/"):
    for file in files:
        if file.endswith(".mp4"):
            file_paths[file.split('.')[0]] = os.path.join(root, file)
            
file_paths

In [3]:
extractAudioFromClips()

ValueError: MoviePy couldn't find the codec associated with the filename. Provide the 'codec' parameter in write_audiofile.

### NLQ template queries

In [31]:
def getTemplateCounts(nlq_dataset):
    json_data = nlq_dataset.raw_data_formatted
    query_templates = list(map(lambda a : (a[0], a[1]["query_templates"]), json_data.items()))
    query_templates_arr = list(map(lambda a : a[1], query_templates))
    flat_query_templates = list(np.concatenate(query_templates_arr).flat)
    return Counter(flat_query_templates)

In [32]:
# counts of query templates in NLQ train set
unique_templates = getTemplateCounts(nql_dataset_train)
unique_templates.most_common()

[('Objects: Where is object X before / after event Y?', 1760),
 ('Place: Where did I put X?', 1676),
 ('Objects: Where is object X?', 1455),
 ('Objects: What did I put in X?', 1263),
 ('Objects: How many X’s? (quantity question)', 967),
 ('Objects: In what location did I see object X ?', 922),
 ('Objects: What X did I Y?', 878),
 ('Objects: What X is Y?', 853),
 ('Objects: State of an object', 569),
 ('People: Who did I interact with when I did activity X?', 298),
 ('Objects: Where is my object X?', 261),
 ('People: Who did I talk to in location X?', 224),
 ('People: When did I talk to or interact with person with role X?', 103),
 (None, 62)]

In [33]:
# counts of query templates in NLQ val set
unique_templates_val = getTemplateCounts(nql_dataset_val)
unique_templates_val.most_common()

[('Objects: Where is object X before / after event Y?', 644),
 ('Place: Where did I put X?', 626),
 ('Objects: What did I put in X?', 476),
 ('Objects: Where is object X?', 447),
 ('Objects: What X did I Y?', 312),
 ('Objects: What X is Y?', 306),
 ('Objects: How many X’s? (quantity question)', 300),
 ('Objects: In what location did I see object X ?', 293),
 ('Objects: State of an object', 168),
 ('People: Who did I interact with when I did activity X?', 102),
 ('People: Who did I talk to in location X?', 83),
 ('Objects: Where is my object X?', 77),
 ('People: When did I talk to or interact with person with role X?', 25),
 (None, 15)]

In [39]:
# check which queries have no templates
def getNullTemplateData(nlq_dataset):
    json_data = nlq_dataset.raw_data_formatted
    no_templates = []
    for k,v in json_data.items():
        for q, qt in zip(v["sentences"], v["query_templates"]):
            if qt == None:
                no_templates.append((k, q))
    return no_templates

In [ ]:
# show the clip id and query when there is no template in NLQ train set
getNullTemplateData(nql_dataset_train)

In [38]:
json_data = nql_dataset_train.raw_data_formatted
no_templates = []
for k,v in json_data.items():
    for q, qt in zip(v["sentences"], v["query_templates"]):
        if qt == None:
            no_templates.append((k, q))
no_templates

[('77a2e39b-4982-4c53-9a98-e9c7708721c6',
  'where did i put the box with wooden tiles?'),
 ('e0b0ee85-ad8f-47de-ba8b-35c147d84f1c', 'who did i talk to in the house?'),
 ('e0b0ee85-ad8f-47de-ba8b-35c147d84f1c',
  'who did i interact with  while walking in the house?'),
 ('b66e0c62-810f-40ba-a453-050fe752ea67',
  'where was the glass jug before i picked it up?'),
 ('0ad00ff1-054b-4843-ba3a-8fda76311e0c', 'where did i put the hat?'),
 ('4b128b10-8af3-40c9-bd92-4bedb8a0ab82',
  'what numbers did i see on the oven screen?'),
 ('64571a50-3433-4002-9de9-be6d5ded11a7',
  'in what location did i see the tissue paper?'),
 ('64571a50-3433-4002-9de9-be6d5ded11a7', 'where is the phone?'),
 ('acc040c0-82ed-4a79-8f12-759477b5775a', 'where did i pour the dirty water?'),
 ('5e5656d7-83d3-45db-8f97-601328801fd5', 'where did i dispose cabbage?'),
 ('483ddc10-9c9b-4dc7-97fc-86fba1033361',
  'where was the circular saw before i moved it?'),
 ('04c23dbd-f207-4359-a9d7-a10669c4938e',
  'where did i drop the

In [29]:
import moviepy.editor as mp
import torch
from tqdm import tqdm

In [7]:
video = mp.VideoFileClip("/scratch/snagabhushan_umass_edu/dataset/v1/clips/000eba33-8d14-446a-b016-19bd50e9a3b9.mp4")

In [25]:
audio_features = torch.load("/scratch/snagabhushan_umass_edu/dataset/v1/audio_features/000eba33-8d14-446a-b016-19bd50e9a3b9.pt")
audio_features.shape

torch.Size([47089, 1024])

In [8]:
features = torch.load("/scratch/shantanuagar_umass_edu/ego4d/saved_clip_features/000eba33-8d14-446a-b016-19bd50e9a3b9.pt")
features.shape

torch.Size([901, 2304])

In [30]:
j = 0 
for i, frame in tqdm(enumerate(video.iter_frames())):
    j = i
print(j)

14401it [02:40, 89.99it/s]

[[[86 79 79]
  [86 79 79]
  [87 80 80]
  ...
  [68 66 62]
  [68 66 62]
  [68 66 62]]

 [[86 79 79]
  [86 79 79]
  [87 80 80]
  ...
  [68 66 62]
  [68 66 62]
  [68 66 62]]

 [[86 79 79]
  [86 79 79]
  [87 80 80]
  ...
  [68 66 62]
  [68 66 62]
  [68 66 62]]

 ...

 [[27 25 26]
  [27 25 26]
  [27 25 26]
  ...
  [71 46 16]
  [71 46 16]
  [71 46 16]]

 [[24 22 23]
  [24 22 23]
  [24 22 23]
  ...
  [71 46 16]
  [71 46 16]
  [71 46 16]]

 [[24 22 23]
  [24 22 23]
  [24 22 23]
  ...
  [71 46 16]
  [71 46 16]
  [71 46 16]]]


In [26]:
47089 / 901

52.263041065482795

In [ ]:
clip.duration

### sampling ego4d.json for NLQ

In [14]:
ego4d_json = None
with open(r'S:\umass\696ds\fb-ego4d\ego4d_data\ego4d.json','r') as f:
    ego4d_json = json.load(f)
def sampleNLQEgo4d(filepath):
    nlq_json = None
    with open(filepath,'r') as f:
        nlq_json = json.load(f)
    nlq_vids = nlq_json['videos']
    nlq_vids_ids = list(map(lambda a : a['video_uid'], nlq_vids))
    return list(filter(lambda a : nlq_vids_ids.count(a['video_uid'])>0, ego4d_json['videos']))
vid_train = sampleNLQEgo4d(r'S:\umass\696ds\fb-ego4d\sample_nlq_train.json')
vid_val = sampleNLQEgo4d(r'S:\umass\696ds\fb-ego4d\sample_nlq_test.json')
vid_test = sampleNLQEgo4d(r'S:\umass\696ds\fb-ego4d\sample_nlq_val.json')
train_json = deepcopy(ego4d_json)
val_json = deepcopy(ego4d_json)
test_json = deepcopy(ego4d_json)
train_json['videos'] = vid_train
test_json['videos'] = vid_test
val_json['videos'] = vid_val
ego4d_json['videos'] = vid_train+vid_test+vid_val
with open(r'S:\umass\696ds\ego4d\sample_ego4d_train.json','w') as f:
    json.dump(train_json, f)
with open(r'S:\umass\696ds\ego4d\sample_ego4d_test.json','w') as f:
    json.dump(test_json, f)
with open(r'S:\umass\696ds\ego4d\sample_ego4d_val.json','w') as f:
    json.dump(val_json, f)
with open(r'S:\umass\696ds\ego4d\sample_ego4d.json','w') as f:
    json.dump(ego4d_json, f)

In [ ]:
with open(r'S:\umass\696ds\fb-ego4d\ego4d_data\v1\annotations\narration.json','r') as f:
    print(f.read(10000))

### video + narrations json

In [2]:
from utils.data_loader import MEMEDataLoader
ego4d_path = r'S:\umass\696ds\ego4d\sample_ego4d.json'
narr_path = r'S:\umass\696ds\fb-ego4d\ego4d_data\v1\annotations\narration.json'
dl_obj = MEMEDataLoader(json_path=ego4d_path, narrations_path=narr_path)

In [3]:
dl_obj.get_video_json('9b49246f-30e9-476f-ab8c-56a1bcb1d936')

{'video_uid': '9b49246f-30e9-476f-ab8c-56a1bcb1d936',
 'duration_sec': 3553.0500000000006,
 'scenarios': ['Cleaning / laundry', 'Eating', 'Working at desk'],
 'video_metadata': {'fps': 30.0,
  'num_frames': 106591,
  'video_codec': 'libvpx-vp9',
  'display_resolution_width': 1440,
  'display_resolution_height': 1080,
  'sample_resolution_width': 1440,
  'sample_resolution_height': 1080,
  'mp4_duration_sec': 3553.03,
  'video_start_sec': 0.0210286,
  'video_duration_sec': 3553.03,
  'audio_start_sec': 0.0,
  'audio_duration_sec': 3553.02,
  'video_start_pts': 323,
  'video_duration_pts': 54574592,
  'video_base_numerator': 1,
  'video_base_denominator': 15360,
  'audio_start_pts': 0,
  'audio_duration_pts': 170544880,
  'audio_base_numerator': 1,
  'audio_base_denominator': 48000},
 'split_em': 'train',
 'split_av': None,
 'split_fho': None,
 's3_location': 's3://ego4d-kaust/public/v1/full_scale/9b49246f-30e9-476f-ab8c-56a1bcb1d936',
 'manifold_path': 'manifold://ego4d_fair/tree/interm